spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 4
logging:
  level:
    org:
      hibernate: info
