apiVersion: v1
kind: Service
metadata:
  name: hailor-api-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    - port: 81
      protocol: TCP
      targetPort: 443
  selector:
    app: hailor-api
